import { test, expect, type Page } from '@playwright/test';
async function signIn(page: Page, name: string) {
  await page.goto('/');
  await page.getByRole('textbox', { name: 'School email' }).fill(name + '@mymail.mapua.edu.ph');
  await page.getByRole('button', { name: 'Continue in demo mode' }).click();
  await expect(page.getByRole('heading', { name: 'Select Your Study Topics' })).toBeVisible();
}
test('two browser sessions match, exchange once, preserve drafts on failure and rematch', async ({ browser }) => {
  const first = await browser.newContext();
  const second = await browser.newContext();
  const a = await first.newPage(), b = await second.newPage();
  const errors: string[] = [];
  a.on('pageerror', error => errors.push(error.message));
  b.on('pageerror', error => errors.push(error.message));
  await signIn(a, 'first');
  await signIn(b, 'second');
  await a.locator('#start-chat-btn').click();
  await b.locator('#start-chat-btn').click();
  await expect(a.locator('#chat-header')).toBeVisible();
  await expect(b.locator('#chat-header')).toBeVisible();
  await a.getByRole('textbox', { name: 'Chat message' }).fill('Hello from the first student');
  await expect(b.getByText(/is typing/)).toBeVisible();
  await a.locator('#send-message-btn').click();
  await expect(b.getByText('Hello from the first student', { exact: true })).toHaveCount(1);
  await expect(a.getByText('Hello from the first student', { exact: true })).toHaveCount(1);
  await b.getByRole('textbox', { name: 'Chat message' }).fill('Hello back');
  await b.locator('#send-message-btn').click();
  await expect(a.getByText('Hello back', { exact: true })).toHaveCount(1);
  await a.route('**/api/chat/send', route => route.fulfill({ status: 503, json: { error: 'Test delivery failure' } }));
  await a.getByRole('textbox', { name: 'Chat message' }).fill('Keep this draft');
  await a.locator('#send-message-btn').click();
  await expect(a.getByRole('alert')).toHaveText('Test delivery failure');
  await expect(a.getByRole('textbox', { name: 'Chat message' })).toHaveValue('Keep this draft');
  await a.unroute('**/api/chat/send');
  await a.locator('#leave-chat-btn').click();
  await expect(b.getByText('Peer disconnected from this session')).toBeVisible();
  await expect(b.getByText('Hello back', { exact: true })).toHaveCount(0);
  await b.locator('#next-match-btn').click();
  await expect(b.getByText(/Finding active Mapúa study peers/)).toBeVisible();
  await a.locator('#start-chat-btn').click();
  await expect(a.locator('#chat-header')).toBeVisible();
  await expect(b.locator('#chat-header')).toBeVisible();
  await a.locator('#logout-btn').click();
  await b.locator('#logout-btn').click();
  expect(errors).toEqual([]);
  await first.close(); await second.close();
});
test('HTTP fallback matches and delivers when WebSockets are unavailable', async ({ browser }) => {
  const contexts = await Promise.all([browser.newContext(), browser.newContext()]);
  for (const context of contexts) await context.addInitScript(() => {
    window.WebSocket = class { constructor() { throw new Error('Blocked for fallback test'); } } as any;
  });
  const [a, b] = await Promise.all(contexts.map(c => c.newPage()));
  await signIn(a, 'fallback-a'); await signIn(b, 'fallback-b');
  await a.locator('#start-chat-btn').click(); await b.locator('#start-chat-btn').click();
  await expect(a.locator('#chat-header')).toBeVisible();
  await expect(b.locator('#chat-header')).toBeVisible();
  await a.getByRole('textbox', { name: 'Chat message' }).fill('HTTP fallback works');
  await a.locator('#send-message-btn').click();
  await expect(b.getByText('HTTP fallback works', { exact: true })).toHaveCount(1);
  await a.locator('#logout-btn').click(); await b.locator('#logout-btn').click();
  await Promise.all(contexts.map(c => c.close()));
});
test('mobile layout, theme persistence, demo chat and music controls', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 });
  await page.emulateMedia({ colorScheme: 'light' });
  await page.goto('/');
  await expect(page.locator('html')).not.toHaveClass('dark');
  await page.locator('#dark-mode-toggle-btn').click();
  await expect(page.locator('html')).toHaveClass('dark');
  await page.reload();
  await expect(page.locator('html')).toHaveClass('dark');
  await signIn(page, 'mobile');
  await page.locator('#start-chat-btn').click();
  await page.locator('#simulate-peer-btn').click();
  await expect(page.getByText('Demo conversation with a simulated study partner.')).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Chat message' })).toBeInViewport();
  const overflow = await page.evaluate(() => [...document.querySelectorAll('body *')].filter(el => {
    const style = getComputedStyle(el); const box = el.getBoundingClientRect();
    return style.position === 'fixed' && box.right > innerWidth + 1;
  }).length);
  expect(overflow).toBe(0);
  await page.screenshot({ path: 'test-results/mobile-chat.png' });
  await expect(page.getByRole('region', { name: 'Study music player' })).toHaveCount(0);
  await page.locator('#music-play-toggle-btn').click();
  await expect(page.getByRole('region', { name: 'Study music player' })).toBeVisible();
  await page.getByRole('button', { name: 'Close music player' }).click();
  await expect(page.getByRole('region', { name: 'Study music player' })).toHaveCount(0);
  await page.locator('#logout-btn').click();
});
test('session restores after refresh and invalid emails show a readable error', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Continue in demo mode' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeInViewport();
  await page.screenshot({ path: 'test-results/desktop-login.png' });
  await signIn(page, 'restore');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Select Your Study Topics' })).toBeVisible();
  await page.locator('#logout-btn').click();
  await page.getByRole('textbox', { name: 'School email' }).fill('student@example.com');
  await page.getByRole('button', { name: 'Continue in demo mode' }).click();
  await expect(page.getByText('Enter a valid Mapúa school email address.')).toBeVisible();
});
