import type { DrawChoice } from './src/data/drawGuess';

// Curated, server-only phrases. Each row is a category/difficulty pool.
const pools: Record<string, [string, string, string]> = {
  animals: [
    'cat|dog|rabbit|horse|cow|pig|sheep|goat|duck|chicken|fish|shark|whale|dolphin|octopus|crab|lobster|starfish|jellyfish|turtle|snake|frog|crocodile|lion|tiger|bear|elephant|giraffe|zebra|monkey|gorilla|panda|koala|kangaroo|penguin|owl|eagle|parrot|butterfly|bee',
    'hedgehog|porcupine|raccoon|squirrel|chipmunk|hamster|guinea pig|chameleon|iguana|gecko|salamander|seahorse|stingray|swordfish|pufferfish|narwhal|walrus|sea lion|flamingo|peacock|pelican|woodpecker|toucan|ostrich|hummingbird|vulture|bat|moth|dragonfly|ladybug|grasshopper|praying mantis|ant colony|snail|slug|centipede|scorpion|tarantula|platypus|armadillo',
    'beaver dam|bird nest|hermit crab|caterpillar cocoon|salmon jumping upstream|camel caravan|wolf howling at the moon|bear catching fish|penguin sliding on ice|frog on a lily pad|ducklings following their mother|puppy chasing its tail|cat in a cardboard box|parrot on a pirate shoulder|squirrel hiding an acorn|eagle carrying a fish|spider spinning a web|mole digging a tunnel|flock of migrating geese|sheep being sheared|horse jumping a fence|elephant spraying water|giraffe eating tree leaves|dog catching a frisbee|monkey peeling a banana|turtle hatching on a beach|owl sleeping in a tree|otter floating on its back|kangaroo carrying a joey|butterfly emerging from a cocoon',
  ],
  food: [
    'apple|banana|orange|lemon|lime|pear|peach|grapes|watermelon|pineapple|strawberry|cherry|coconut|mango|carrot|potato|tomato|onion|corn|broccoli|mushroom|bread|egg|cheese|pizza|burger|hot dog|taco|donut|cookie|cake|ice cream|popcorn|candy|chocolate|coffee|tea|milk|juice|water bottle',
    'pancake stack|waffle|croissant|bagel|pretzel|cinnamon roll|cupcake|birthday cake|banana split|ice cream sandwich|fruit salad|vegetable soup|spaghetti|lasagna|sushi roll|dumpling|ramen bowl|fried rice|spring roll|grilled cheese|french fries|onion rings|baked potato|stuffed pepper|fried chicken|barbecue skewers|steak|salmon fillet|milkshake|bubble tea|hot chocolate|lemonade pitcher|smoothie|cereal bowl|peanut butter jar|honey jar|salt shaker|pepper grinder|lollipop|cotton candy',
    'chef tossing pizza dough|overflowing soda|melting ice cream cone|burnt toast|chocolate fountain|gingerbread house|picnic basket|breakfast in bed|food truck|buffet table|wedding cake|cooking over a campfire|roasting marshmallows|squeezing a lemon|peeling an orange|chopping vegetables|flipping a pancake|rolling sushi|kneading bread dough|decorating cookies|spilled coffee|pouring maple syrup|giant sandwich|midnight snack|eating with chopsticks|blowing out birthday candles|carrying a tray of drinks|popping corn in a pan|making a smoothie|restaurant menu',
  ],
  objects: [
    'chair|table|bed|pillow|blanket|sofa|lamp|clock|mirror|door|window|key|lock|umbrella|hat|shoe|sock|glove|scarf|belt|bag|backpack|wallet|coin|comb|toothbrush|soap|towel|bucket|broom|mop|sponge|plate|bowl|cup|fork|spoon|knife|scissors|pencil',
    'rocking chair|bunk bed|bookshelf|coat rack|ceiling fan|alarm clock|hourglass|magnifying glass|binoculars|telescope|compass|thermometer|measuring tape|toolbox|hammer|screwdriver|wrench|pliers|paint roller|watering can|garden hose|flowerpot|sewing machine|safety pin|zipper|button|clothes hanger|laundry basket|ironing board|vacuum cleaner|trash can|recycling bin|shopping cart|wheelbarrow|step ladder|flashlight|candle holder|picture frame|snow globe|music box',
    'message in a bottle|ship in a bottle|jack in the box|treasure chest|broken umbrella|suitcase on wheels|bag full of groceries|chair with a missing leg|grandfather clock|folding camping chair|keys locked inside a car|stack of moving boxes|tangled necklace|jar of spare change|overstuffed closet|washing clothes by hand|hanging laundry to dry|changing a light bulb|assembling furniture|wrapping a gift|opening a stubborn jar|fixing a flat tire|packing a suitcase|hiding under a blanket|rolling up a carpet|wall covered in sticky notes|tools hanging on a wall|balancing plates|lost sock under a bed|pillow fort',
  ],
  nature: [
    'sun|moon|star|cloud|rain|snow|rainbow|lightning|tree|leaf|flower|grass|rock|mountain|hill|river|lake|ocean|beach|island|desert|forest|cactus|volcano|waterfall|wave|sand|shell|acorn|pinecone|seed|root|branch|bush|pond|iceberg|cave|mud|puddle|fire',
    'sunflower|rose|tulip|daisy|lotus|lily pad|palm tree|pine tree|willow tree|bamboo|fern|moss|seaweed|coral reef|sand dune|glacier|canyon|cliff|geyser|hot spring|tornado|hurricane|blizzard|hailstorm|fog|frost|dewdrop|icicle|snowflake|full moon|crescent moon|shooting star|comet|meteor|constellation|solar eclipse|aurora|tide pool|river delta|oasis',
    'sunrise over mountains|sunset over the ocean|lightning striking a tree|double rainbow|eruption of a volcano|avalanche on a mountain|flooded street|tree roots breaking pavement|leaves blowing in the wind|snow covered forest|frozen waterfall|desert sandstorm|moon reflected in a lake|footprints in the snow|message written in sand|rain falling on a pond|flowers growing through concrete|forest after a fire|mountain reflected in water|cloud shaped like a heart|changing seasons|melting glacier|wind bending palm trees|river flowing into the sea|rock arch over water|crystal inside a geode|mushrooms on a fallen log|seedling reaching for sunlight|wildflowers on a hillside|sunbeam through clouds',
  ],
  places: [
    'house|school|hospital|castle|church|mosque|temple|library|bank|store|bakery|cafe|restaurant|hotel|airport|station|bridge|road|park|playground|zoo|farm|barn|beach hut|tent|igloo|lighthouse|tower|pyramid|fountain|stadium|cinema|museum|garage|pool|kitchen|bedroom|bathroom|garden|balcony',
    'treehouse|windmill|water tower|fire station|police station|post office|gas station|car wash|supermarket|shopping mall|amusement park|skate park|aquarium|planetarium|observatory|greenhouse|botanical garden|dairy farm|vineyard|harbor|marina|fishing village|mountain cabin|campsite|railway crossing|subway platform|bus stop|parking lot|traffic roundabout|toll booth|ski resort|bowling alley|ice rink|concert hall|theater stage|art gallery|courthouse|factory|warehouse|construction site',
    'city skyline at night|floating market|underwater city|abandoned train station|castle on a cliff|house on stilts|restaurant on a boat|village inside a mountain|airport control tower|rooftop garden|maze made of hedges|secret room behind a bookshelf|bridge opening for a ship|busy street market|lighthouse in a storm|tiny house on wheels|train entering a tunnel|road through a forest|cafe on a rainy day|ancient ruins in a jungle|snowy mountain village|house surrounded by water|desert ghost town|crowded subway carriage|town square with a fountain|house shaped like a shoe|pirate port|space station interior|mountain road with hairpin turns|castle drawbridge',
  ],
  sports: [
    'football|basketball|tennis|baseball|volleyball|badminton|golf|boxing|swimming|running|cycling|skiing|surfing|skating|bowling|archery|fencing|wrestling|karate|yoga|hiking|climbing|rowing|sailing|diving|soccer goal|tennis racket|baseball bat|golf club|bowling ball|skateboard|surfboard|bicycle|helmet|medal|trophy|whistle|dumbbell|trampoline|jump rope',
    'table tennis|ice hockey|field hockey|rugby|cricket|lacrosse|water polo|handball|softball|kickboxing|judo|taekwondo|sumo wrestling|weightlifting|gymnastics|figure skating|snowboarding|skateboarding ramp|rock climbing wall|pole vault|high jump|long jump|hurdles|relay race|marathon|triathlon|horse racing|equestrian jumping|canoeing|kayaking|windsurfing|kitesurfing|paragliding|skydiving|scuba diving|snorkeling|bungee jumping|zipline|balance beam|parallel bars',
    'basketball slam dunk|soccer penalty kick|baseball home run|tennis overhead smash|volleyball spike|goalkeeper saving a shot|cyclist crossing the finish line|runner passing a relay baton|surfer riding a huge wave|skier jumping off a ramp|ice skater spinning|boxer in the corner|archer hitting a bullseye|gymnast on a balance beam|swimmer doing a backstroke|bowler knocking down all pins|golf ball landing in a bunker|climber reaching the summit|rowers working together|crowd doing the wave|coach drawing a strategy|referee showing a red card|victory podium|sports team huddle|athlete tying shoelaces|weightlifter dropping a barbell|tennis ball stuck in a fence|bicycle with training wheels|ski lift on a mountain|tug of war',
  ],
  technology: [
    'phone|computer|laptop|tablet|keyboard|mouse|screen|camera|television|radio|headphones|speaker|microphone|printer|robot|drone|rocket|satellite|battery|plug|cable|light bulb|switch|calculator|remote control|joystick|game console|watch|fan|fridge|oven|toaster|blender|kettle|washing machine|elevator|escalator|car|train|airplane',
    'smartwatch|webcam|tripod|camera lens|memory card|USB drive|hard drive|computer chip|circuit board|graphics card|server rack|wifi router|charging dock|solar panel|wind turbine|power bank|barcode scanner|cash register|vending machine|ATM|traffic light|security camera|doorbell camera|walkie talkie|megaphone|record player|projector|VR headset|3D printer|robot arm|electric scooter|electric car|self driving car|remote controlled car|space rover|submarine|helicopter|hot air balloon|cable car|steam engine',
    'robot vacuum stuck under a sofa|phone with a cracked screen|laptop with a low battery|computer overheating|tangled charging cables|robot delivering a package|drone taking a photograph|rocket launching into space|astronaut repairing a satellite|printer jam|video call with frozen faces|camera on a selfie stick|smart home control panel|charging an electric car|car stuck in traffic|train leaving a station|helicopter rescuing a hiker|submarine exploring a shipwreck|robot playing chess|solar powered house|wind farm on a hill|computer recycling center|satellite orbiting Earth|phone dropped in water|headphones with a broken wire|robot painting a portrait|3D printing a toy|automatic door opening|elevator full of people|searching for a wifi signal',
  ],
  campus: [
    'notebook|textbook|eraser|ruler|marker|crayon|pen|chalk|blackboard|whiteboard|desk|locker|uniform|graduation cap|diploma|school bell|school bus|lunchbox|book|paper|folder|binder|stapler|paperclip|globe|map|test tube|microscope|beaker|flask|report card|ID card|name tag|bulletin board|lecture hall|classroom|canteen|dormitory|school gate|flagpole',
    'pencil case|pencil sharpener|drawing compass|protractor|graph paper|index cards|sticky note|highlighter|hole punch|lab coat|safety goggles|Bunsen burner|periodic table|skeleton model|anatomy model|science poster|notice board|attendance sheet|exam paper|answer sheet|study timetable|campus map|library card|book cart|reading lamp|desk organizer|student planner|class schedule|group project|science fair|art exhibition|school play|debate podium|graduation gown|school mascot|sports day|campus fountain|student lounge|dorm bunk bed|laboratory sink',
    'student sleeping during a lecture|studying the night before an exam|raising a hand in class|teacher writing on the board|backpack bursting with books|forgotten homework|racing to catch the school bus|stack of ungraded papers|library full of students|group presenting a project|volcano science experiment|graduation caps flying|long line at the canteen|dorm room with messy laundry|lost student looking at a map|reading under a desk|borrowing a pencil|textbook used as a pillow|coffee beside a pile of notes|exam clock running out|student carrying too many books|class photo|broken classroom projector|locker full of sports gear|sharing an umbrella after class|school garden planting day|whiteboard covered in equations|late student sneaking into class|campus club signup booth|paper airplane in a classroom',
  ],
  actions: [
    'walking|jumping|dancing|singing|reading|writing|drawing|painting|cooking|eating|drinking|sleeping|sitting|standing|waving|clapping|laughing|crying|sneezing|yawning|smiling|frowning|pointing|kicking|throwing|catching|pushing|pulling|lifting|crawling|stretching|digging|sweeping|mopping|washing|driving|flying|fishing|knitting|sewing',
    'brushing teeth|washing hands|combing hair|tying shoes|buttoning a shirt|folding clothes|doing dishes|walking a dog|feeding a cat|watering plants|planting a tree|building a snowman|making a sandcastle|flying a kite|blowing bubbles|skipping stones|riding a horse|paddling a canoe|playing guitar|playing piano|playing drums|juggling balls|doing a cartwheel|doing a handstand|balancing on one foot|hula hooping|rolling dice|shuffling cards|opening a present|lighting a candle|taking a photo|waving goodbye|shaking hands|giving a high five|hugging a friend|carrying a baby|pushing a stroller|raking leaves|shoveling snow|picking apples',
    'trying to catch a falling plate|carrying water in a leaky bucket|walking on a tightrope|sneaking past a sleeping dog|chasing a runaway hat|looking for lost glasses|tiptoeing through puddles|balancing books on your head|sliding down a banister|hanging a picture crookedly|attempting to whistle|trying to reach a high shelf|getting tangled in a hammock|climbing through a window|carrying a sofa up stairs|swinging across a river|hiding behind a curtain|dancing in the rain|walking against strong wind|running from a swarm of bees|pushing a stalled car|trying to open a stuck door|dropping a stack of papers|wiping fog off a mirror|following a treasure map|building a house of cards|blowing a giant bubble|reading a book upside down|catching snowflakes on your tongue|stepping over sleeping pets',
  ],
  funny: [
    'clown|ghost|alien|monster|dragon|unicorn|mermaid|pirate|wizard|witch|fairy|superhero|zombie|vampire|giant|dwarf|goblin|troll|genie|snowman|scarecrow|puppet|teddy bear|rubber duck|whoopee cushion|banana peel|fake mustache|party hat|balloon animal|magic wand|crystal ball|flying saucer|witch broom|pirate hat|magic carpet|treasure map|golden goose|beanstalk|pumpkin carriage|talking tree',
    'cat wearing sunglasses|dog wearing a tie|penguin in a hat|bear riding a bicycle|frog wearing a crown|duck with an umbrella|mouse lifting weights|rabbit doing magic|elephant on roller skates|giraffe wearing a scarf|shark with braces|octopus playing drums|crab wearing boots|snake wearing a bow tie|owl holding coffee|panda doing yoga|dinosaur with a backpack|unicorn eating pizza|dragon brushing its teeth|ghost wearing sneakers|alien eating noodles|robot with a mustache|wizard riding a scooter|pirate on a skateboard|mermaid with a phone|superhero doing laundry|zombie eating salad|vampire at the dentist|witch cooking spaghetti|giant holding a tiny cup|snowman on vacation|scarecrow at a dance|teddy bear astronaut|rubber duck captain|monster wearing slippers|clown fishing|genie stuck in a teapot|fairy carrying groceries|troll playing violin|goblin baking cookies',
    'cat running a restaurant|dog interviewing for a job|penguins having a board meeting|elephant hiding behind a flower|giraffe trying to fit in a car|dinosaur stuck in an elevator|dragon roasting marshmallows with its breath|unicorn waiting at a traffic light|ghost afraid of a spider|alien getting a parking ticket|robot falling asleep in class|wizard losing his magic wand|pirate searching for wifi|mermaid ordering takeaway|superhero stuck in a revolving door|zombie running a marathon|vampire applying sunscreen|witch taking a driving test|giant using a phone booth|snowman sitting in a sauna|scarecrow scared of birds|teddy bears having a picnic|rubber duck leading a parade|monster under a bed reading a book|clown trying to be serious|genie granting a sandwich wish|fairy stuck in bubble gum|troll guarding a tiny bridge|goblin selling lemonade|moon wearing pajamas',
  ],
};

export const DRAW_PROMPTS: DrawChoice[] = Object.entries(pools).flatMap(([category, rows]) =>
  rows.flatMap((row, difficultyIndex) =>
    row.split('|').map((word, index) => ({
      id: `${category}-${difficultyIndex}-${index}`,
      word,
      category: category as DrawChoice['category'],
      difficulty: (['easy', 'medium', 'hard'] as const)[difficultyIndex]!,
    })),
  ),
);
